const __dataProducts = [
    {
        src: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-1-1.jpg",
        src2: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-1-2.jpg",
        c: "Snack",
        n: "Cà phê Đany Blend",
        s: "NestFood",
        newP: "$28.85",
        oldP: "$32.8",
        percent: "57.83",
        amount: "2.9",
        percent2: "45.86",
        value1: 61,
        value2: 133,
    },
    {
        src: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-2-1.jpg",
        src2: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-2-2.jpg",
        c: "Hodo Foods",
        n: "Hạt điều rang muối ớt",
        s: "Stouffer",
        newP: "$52.85",
        oldP: "$55.8",
        percent: "42.62",
        amount: "2.1",
        percent2: "64.10",
        value1: 100,
        value2: 156,
    },
    {
        src: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-3-1.jpg",
        src2: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-3-2.jpg",
        c: "Snack",
        n: "Đậu phộng Broccoli Chedda",
        s: "StarKist",
        newP: "$48.85",
        oldP: "$52.8",
        percent: "7.64",
        amount: "0.4",
        percent2: "30.08",
        value1: 40,
        value2: 133,
    },
    {
        src: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-4-1.jpg",
        src2: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-4-2.jpg",
        c: "Vegetables",
        n: "Hạt điều rang muối mè Sahale",
        s: "NestFood",
        newP: "$17.85",
        oldP: "$19.8",
        percent: "77.95",
        amount: "3.9",
        percent2: "60.17",
        value1: 71,
        value2: 118,
    },
    {
        src: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-5-1.jpg",
        src2: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-5-2.jpg",
        c: "Pet Foods",
        n: "Bánh dừa làm từ dừa nguyên chất Coconut Flakes",
        s: "NestFood",
        newP: "$23.85",
        oldP: "$25.8",
        percent: "93.32",
        amount: "4.7",
        percent2: "31.78",
        value1: 34,
        value2: 107,
    },
    {
        src: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-6-1.jpg",
        src2: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-6-2.jpg",
        c: "Hodo Foods",
        n: "Bánh sô cô la rắc đậu phộng Mighty Muffin loại lớn",
        s: "NestFood",
        newP: "$54.85",
        oldP: "$55.8",
        percent: "85.45",
        amount: "4.3",
        percent2: "86.27",
        value1: 88,
        value2: 102,
    },
    {
        src: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-7-1.jpg",
        src2: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-7-2.jpg",
        c: "Meats",
        n: "Hạt dẻ",
        s: "NestFood",
        newP: "$32.85",
        oldP: "$33.8",
        percent: "67.61",
        amount: "3.4",
        percent2: "9.89",
        value1: 18,
        value2: 182,
    },
    {
        src: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-8-1.jpg",
        src2: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-8-2.jpg",
        c: "Snack",
        n: "Tinh dầu Yuja Niacin chiết xuất từ cam tươi",
        s: "NestFood",
        newP: "$35.85",
        oldP: "$37.8",
        percent: "27.52",
        amount: "1.4",
        percent2: "99.47",
        value1: 188,
        value2: 189,
    },
    {
        src: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-9-1.jpg",
        src2: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-9-2.jpg",
        c: "Coffes",
        n: "Cà phê Altura nguyên chất",
        s: "Old El Paso",
        newP: "$23.85",
        oldP: "$25.8",
        percent: "30.33",
        amount: "1.5",
        percent2: "31.38",
        value1: 59,
        value2: 188,
    },
    {
        src: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-10-1.jpg",
        src2: "http://wp.alithemes.com/html/nest/demo/assets/imgs/shop/product-10-2.jpg",
        c: "Cream",
        n: "Mặt nạ dưỡng da kiêm làm trắng da Pukka",
        s: "Tyson",
        newP: "$22.85",
        oldP: "$24.8",
        percent: "58.88",
        amount: "2.9",
        percent2: "69.81",
        value1: 74,
        value2: 106,
    },
];
